# Generated by Django 5.2.1 on 2025-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vote_delete_review_remove_choice_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя голосующего'),
        ),
    ]
