# Generated by Django 5.2.1 on 2025-05-31 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_poll_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вопроса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_questions', to='polls.poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_questions', to='polls.question')),
            ],
            options={
                'verbose_name': 'Вопрос в опросе',
                'verbose_name_plural': 'Вопросы в опросах',
                'ordering': ['order'],
                'unique_together': {('poll', 'question')},
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(related_name='polls', through='polls.PollQuestion', to='polls.question', verbose_name='Вопросы'),
        ),
    ]
